-- Generated RLS SQL
DO $$ BEGIN PERFORM current_setting('app.tenant_id'); EXCEPTION WHEN others THEN PERFORM set_config('app.tenant_id','',false); END $$;
ALTER TABLE "tenant_users" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "tenant_users";
DROP POLICY IF EXISTS tenant_isolation_insert ON "tenant_users";
DROP POLICY IF EXISTS tenant_isolation_update ON "tenant_users";
DROP POLICY IF EXISTS tenant_isolation_delete ON "tenant_users";
CREATE POLICY tenant_isolation_select ON "tenant_users" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "tenant_users" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "tenant_users" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "tenant_users" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "tenant_modules" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "tenant_modules";
DROP POLICY IF EXISTS tenant_isolation_insert ON "tenant_modules";
DROP POLICY IF EXISTS tenant_isolation_update ON "tenant_modules";
DROP POLICY IF EXISTS tenant_isolation_delete ON "tenant_modules";
CREATE POLICY tenant_isolation_select ON "tenant_modules" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "tenant_modules" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "tenant_modules" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "tenant_modules" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "roles";
DROP POLICY IF EXISTS tenant_isolation_insert ON "roles";
DROP POLICY IF EXISTS tenant_isolation_update ON "roles";
DROP POLICY IF EXISTS tenant_isolation_delete ON "roles";
CREATE POLICY tenant_isolation_select ON "roles" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "roles" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "roles" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "roles" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "user_roles";
DROP POLICY IF EXISTS tenant_isolation_insert ON "user_roles";
DROP POLICY IF EXISTS tenant_isolation_update ON "user_roles";
DROP POLICY IF EXISTS tenant_isolation_delete ON "user_roles";
CREATE POLICY tenant_isolation_select ON "user_roles" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "user_roles" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "user_roles" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "user_roles" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "white_brand_configs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "white_brand_configs";
DROP POLICY IF EXISTS tenant_isolation_insert ON "white_brand_configs";
DROP POLICY IF EXISTS tenant_isolation_update ON "white_brand_configs";
DROP POLICY IF EXISTS tenant_isolation_delete ON "white_brand_configs";
CREATE POLICY tenant_isolation_select ON "white_brand_configs" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "white_brand_configs" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "white_brand_configs" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "white_brand_configs" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "audit_events";
DROP POLICY IF EXISTS tenant_isolation_insert ON "audit_events";
DROP POLICY IF EXISTS tenant_isolation_update ON "audit_events";
DROP POLICY IF EXISTS tenant_isolation_delete ON "audit_events";
CREATE POLICY tenant_isolation_select ON "audit_events" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "audit_events" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "audit_events" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "audit_events" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "tenant_subscriptions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "tenant_subscriptions";
DROP POLICY IF EXISTS tenant_isolation_insert ON "tenant_subscriptions";
DROP POLICY IF EXISTS tenant_isolation_update ON "tenant_subscriptions";
DROP POLICY IF EXISTS tenant_isolation_delete ON "tenant_subscriptions";
CREATE POLICY tenant_isolation_select ON "tenant_subscriptions" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "tenant_subscriptions" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "tenant_subscriptions" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "tenant_subscriptions" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_categories" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_categories";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_categories";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_categories";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_categories";
CREATE POLICY tenant_isolation_select ON "menu_online_categories" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_categories" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_categories" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_categories" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_products" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_products";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_products";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_products";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_products";
CREATE POLICY tenant_isolation_select ON "menu_online_products" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_products" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_products" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_products" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_product_images" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_product_images";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_product_images";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_product_images";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_product_images";
CREATE POLICY tenant_isolation_select ON "menu_online_product_images" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_product_images" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_product_images" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_product_images" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_price_variations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_price_variations";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_price_variations";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_price_variations";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_price_variations";
CREATE POLICY tenant_isolation_select ON "menu_online_price_variations" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_price_variations" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_price_variations" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_price_variations" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_modifier_groups" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_modifier_groups";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_modifier_groups";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_modifier_groups";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_modifier_groups";
CREATE POLICY tenant_isolation_select ON "menu_online_modifier_groups" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_modifier_groups" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_modifier_groups" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_modifier_groups" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_modifier_options" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_modifier_options";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_modifier_options";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_modifier_options";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_modifier_options";
CREATE POLICY tenant_isolation_select ON "menu_online_modifier_options" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_modifier_options" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_modifier_options" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_modifier_options" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_product_modifiers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_product_modifiers";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_product_modifiers";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_product_modifiers";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_product_modifiers";
CREATE POLICY tenant_isolation_select ON "menu_online_product_modifiers" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_product_modifiers" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_product_modifiers" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_product_modifiers" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_settings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_settings";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_settings";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_settings";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_settings";
CREATE POLICY tenant_isolation_select ON "menu_online_settings" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_settings" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_settings" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_settings" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_upsell_suggestions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_upsell_suggestions";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_upsell_suggestions";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_upsell_suggestions";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_upsell_suggestions";
CREATE POLICY tenant_isolation_select ON "menu_online_upsell_suggestions" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_upsell_suggestions" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_upsell_suggestions" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_upsell_suggestions" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_combos" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_combos";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_combos";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_combos";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_combos";
CREATE POLICY tenant_isolation_select ON "menu_online_combos" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_combos" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_combos" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_combos" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_combo_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_combo_items";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_combo_items";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_combo_items";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_combo_items";
CREATE POLICY tenant_isolation_select ON "menu_online_combo_items" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_combo_items" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_combo_items" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_combo_items" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_coupons" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_coupons";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_coupons";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_coupons";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_coupons";
CREATE POLICY tenant_isolation_select ON "menu_online_coupons" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_coupons" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_coupons" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_coupons" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_coupon_redemptions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_coupon_redemptions";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_coupon_redemptions";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_coupon_redemptions";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_coupon_redemptions";
CREATE POLICY tenant_isolation_select ON "menu_online_coupon_redemptions" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_coupon_redemptions" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_coupon_redemptions" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_coupon_redemptions" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_loyalty_config" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_loyalty_config";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_loyalty_config";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_loyalty_config";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_loyalty_config";
CREATE POLICY tenant_isolation_select ON "menu_online_loyalty_config" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_loyalty_config" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_loyalty_config" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_loyalty_config" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_cashback_config" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_cashback_config";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_cashback_config";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_cashback_config";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_cashback_config";
CREATE POLICY tenant_isolation_select ON "menu_online_cashback_config" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_cashback_config" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_cashback_config" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_cashback_config" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "menu_online_customer_balances" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "menu_online_customer_balances";
DROP POLICY IF EXISTS tenant_isolation_insert ON "menu_online_customer_balances";
DROP POLICY IF EXISTS tenant_isolation_update ON "menu_online_customer_balances";
DROP POLICY IF EXISTS tenant_isolation_delete ON "menu_online_customer_balances";
CREATE POLICY tenant_isolation_select ON "menu_online_customer_balances" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "menu_online_customer_balances" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "menu_online_customer_balances" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "menu_online_customer_balances" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "store_settings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "store_settings";
DROP POLICY IF EXISTS tenant_isolation_insert ON "store_settings";
DROP POLICY IF EXISTS tenant_isolation_update ON "store_settings";
DROP POLICY IF EXISTS tenant_isolation_delete ON "store_settings";
CREATE POLICY tenant_isolation_select ON "store_settings" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "store_settings" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "store_settings" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "store_settings" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "delivery_pricing_settings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "delivery_pricing_settings";
DROP POLICY IF EXISTS tenant_isolation_insert ON "delivery_pricing_settings";
DROP POLICY IF EXISTS tenant_isolation_update ON "delivery_pricing_settings";
DROP POLICY IF EXISTS tenant_isolation_delete ON "delivery_pricing_settings";
CREATE POLICY tenant_isolation_select ON "delivery_pricing_settings" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "delivery_pricing_settings" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "delivery_pricing_settings" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "delivery_pricing_settings" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "order_manager_orders" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "order_manager_orders";
DROP POLICY IF EXISTS tenant_isolation_insert ON "order_manager_orders";
DROP POLICY IF EXISTS tenant_isolation_update ON "order_manager_orders";
DROP POLICY IF EXISTS tenant_isolation_delete ON "order_manager_orders";
CREATE POLICY tenant_isolation_select ON "order_manager_orders" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "order_manager_orders" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "order_manager_orders" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "order_manager_orders" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "order_manager_order_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "order_manager_order_items";
DROP POLICY IF EXISTS tenant_isolation_insert ON "order_manager_order_items";
DROP POLICY IF EXISTS tenant_isolation_update ON "order_manager_order_items";
DROP POLICY IF EXISTS tenant_isolation_delete ON "order_manager_order_items";
CREATE POLICY tenant_isolation_select ON "order_manager_order_items" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "order_manager_order_items" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "order_manager_order_items" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "order_manager_order_items" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "order_manager_order_item_modifiers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "order_manager_order_item_modifiers";
DROP POLICY IF EXISTS tenant_isolation_insert ON "order_manager_order_item_modifiers";
DROP POLICY IF EXISTS tenant_isolation_update ON "order_manager_order_item_modifiers";
DROP POLICY IF EXISTS tenant_isolation_delete ON "order_manager_order_item_modifiers";
CREATE POLICY tenant_isolation_select ON "order_manager_order_item_modifiers" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "order_manager_order_item_modifiers" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "order_manager_order_item_modifiers" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "order_manager_order_item_modifiers" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "order_manager_order_timeline_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "order_manager_order_timeline_events";
DROP POLICY IF EXISTS tenant_isolation_insert ON "order_manager_order_timeline_events";
DROP POLICY IF EXISTS tenant_isolation_update ON "order_manager_order_timeline_events";
DROP POLICY IF EXISTS tenant_isolation_delete ON "order_manager_order_timeline_events";
CREATE POLICY tenant_isolation_select ON "order_manager_order_timeline_events" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "order_manager_order_timeline_events" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "order_manager_order_timeline_events" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "order_manager_order_timeline_events" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "orders";
DROP POLICY IF EXISTS tenant_isolation_insert ON "orders";
DROP POLICY IF EXISTS tenant_isolation_update ON "orders";
DROP POLICY IF EXISTS tenant_isolation_delete ON "orders";
CREATE POLICY tenant_isolation_select ON "orders" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "orders" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "orders" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "orders" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "order_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "order_items";
DROP POLICY IF EXISTS tenant_isolation_insert ON "order_items";
DROP POLICY IF EXISTS tenant_isolation_update ON "order_items";
DROP POLICY IF EXISTS tenant_isolation_delete ON "order_items";
CREATE POLICY tenant_isolation_select ON "order_items" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "order_items" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "order_items" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "order_items" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "payments";
DROP POLICY IF EXISTS tenant_isolation_insert ON "payments";
DROP POLICY IF EXISTS tenant_isolation_update ON "payments";
DROP POLICY IF EXISTS tenant_isolation_delete ON "payments";
CREATE POLICY tenant_isolation_select ON "payments" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "payments" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "payments" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "payments" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "delivery_routes" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "delivery_routes";
DROP POLICY IF EXISTS tenant_isolation_insert ON "delivery_routes";
DROP POLICY IF EXISTS tenant_isolation_update ON "delivery_routes";
DROP POLICY IF EXISTS tenant_isolation_delete ON "delivery_routes";
CREATE POLICY tenant_isolation_select ON "delivery_routes" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "delivery_routes" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "delivery_routes" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "delivery_routes" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "delivery_drivers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "delivery_drivers";
DROP POLICY IF EXISTS tenant_isolation_insert ON "delivery_drivers";
DROP POLICY IF EXISTS tenant_isolation_update ON "delivery_drivers";
DROP POLICY IF EXISTS tenant_isolation_delete ON "delivery_drivers";
CREATE POLICY tenant_isolation_select ON "delivery_drivers" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "delivery_drivers" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "delivery_drivers" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "delivery_drivers" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "driver_positions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "driver_positions";
DROP POLICY IF EXISTS tenant_isolation_insert ON "driver_positions";
DROP POLICY IF EXISTS tenant_isolation_update ON "driver_positions";
DROP POLICY IF EXISTS tenant_isolation_delete ON "driver_positions";
CREATE POLICY tenant_isolation_select ON "driver_positions" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "driver_positions" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "driver_positions" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "driver_positions" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE "driver_status_history" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_select ON "driver_status_history";
DROP POLICY IF EXISTS tenant_isolation_insert ON "driver_status_history";
DROP POLICY IF EXISTS tenant_isolation_update ON "driver_status_history";
DROP POLICY IF EXISTS tenant_isolation_delete ON "driver_status_history";
CREATE POLICY tenant_isolation_select ON "driver_status_history" FOR SELECT USING (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_insert ON "driver_status_history" FOR INSERT WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_update ON "driver_status_history" FOR UPDATE USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
CREATE POLICY tenant_isolation_delete ON "driver_status_history" FOR DELETE USING (tenant_id = current_setting('app.tenant_id', true));
